#!/usr/bin/env bash

fz(){ fzf --ansi --reverse --height=40% -0 -1 -q "$1"; }

income(){
	eval $(printf '%s\n' "print" "add" "delete" | fz $1)_income
}

read_income(){ in+=("$1"); ii+=("$2"); ((income_total+=$2)); }
read_expense(){ en+=("$1"); ei+=("$2"); ((expense_total+=$2)); }

add_income(){ in+=("$1"); ii+=("$2"); }
add_expense(){ en+=("$1");ei+=("$2");  }

print_expense(){
	printf '\e[4m\e[1m%-12.12s%12.12s\e[m\e[4m%s\n' "expense:" "$((expense_total))" " $cur"
	for i in ${!ei[@]};{ printf '\e[m%-12.12s\e[1m%12.9s\e[m%s\n' "${en[i]}" "$((${ei[i]}))" " $cur";}
}

print_income(){
	printf '\e[4m\e[1m%-12.12s%12.12s\e[m\e[4m%s\n' "income:" "$((income_total))" " $cur"
	for i in ${!in[@]};{ printf '\e[m%-12.12s\e[1m%12.9s\e[m%s\n' "${in[i]}" "$((${ii[i]}))" " $cur";}
}

print_all(){
	echo; print_income; echo; print_expense
		printf '\n\e[1m%s\n' "remaining: $((income_total-expense_total)) $cur"
}

print(){ print_all; }

read_file(){
	while read -r line; do ((i++))
		[[ ! -z "$line" ]] || continue; set $line
		[[ $1 =~ income ]] && { state=income; continue; }
		[[ $1 =~ expense ]] && { state=expense; continue; }
		[[ $state = income ]] && read_income "$1" "$2"
		[[ $state = expense ]] && read_expense "$1" "$2"
	done  < "$budget"
}

print_opts(){ printf '%s\n' "print" "income" "expense"; }

main(){
	budget="$HOME/Dokumenter/budget.tab"
	[[ -f $budget ]] || budget="example.bgt"
	read_file
	eval $(print_opts | fz "$1") $2
}


cur="kr"
main "$@"
