#!/usr/bin/env bash

read_income(){ in[$1]=$2; ii[$1]=$3; ((income_total+=$3)); }
read_expense(){ en[$1]=$2; ei[$1]=$3; ((expense_total+=$3)); }

print_expense(){
	printf '\e[4m\e[1m%-12.12s%12.12s\e[m\e[4m%s\n' "expense:" "$expense_total" " $cur"
	for i in ${!ei[@]};{ printf '\e[m%-12.12s\e[1m%12.9s\e[m%s\n' "${en[i]}" "${ei[i]}" " $cur";}
}

print_income(){
	printf '\e[4m\e[1m%-12.12s%12.12s\e[m\e[4m%s\n' "income:" "$income_total" " $cur"
	for i in ${!in[@]};{ printf '\e[m%-12.12s\e[1m%12.9s\e[m%s\n' "${in[i]}" "${ii[i]}" " $cur";}
}

read_file(){
	while read -r line; do ((i++))
		[[ "$line" =~ .*[a-z].* ]] || continue; set $line
		[[ $1 =~ expense ]] && { state=expense; i=0; continue; }
		[[ $1 =~ income ]] && { state=income; i=0; continue; }
		[[ $state = income ]] && read_income "$i" "$1" "$2"
		[[ $state = expense ]] && read_expense "$i" "$1" "$2"
	done  < "$HOME/Dokumenter/budget.tab"
}

main(){
	cur="kr"
	read_file; echo; print_income; echo; print_expense
	printf '\n\e[1m%s\n' "free capatal: $((income_total-expense_total)) $cur"
}

main "$@" #| fzf --ansi --reverse --height=40%
